#!/bin/bash
# Install Rust and Cargo for the Binder environment
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source $HOME/.cargo/env

# Build and install the streams1d python bindings
maturin develop --features python
